### ISSUE TITLE
Aborts cannot be detected

### ISSUE THREAD

**Issue by ianwremmel** [MathieuTurcotte/node-backoff#15]
As far as I can tell, once abort is called, no event is called and the completion handler doesn't execute.

**Comment by MathieuTurcotte** [comment]
You're right. It's an oversight on my part. Will require adding a new event, but should keep the API compatible. Happy to do it, or you can send me a pull request.

**Comment by ianwremmel** [comment]
I'm happy to send a PR, but I wasn't sure what the best way to do it was. Should it just be an abort event inside the abort method or should the completion callback also get invoked? If the completion handler should also get invoked, should it be called with an error or is it up to the end-developer to put an isAborted check in there?

**Comment by MathieuTurcotte** [comment]
I'll bundle those changes with the next release of the library. Could you try this API on your side and let me know how you find it. Thanks for reporting the issue!

**Comment by erossignon** [comment]
:+1:

**Comment by erossignon** [comment]
@MathieuTurcotte  any idea when ppm module v2.4.2 is due to incorporate this change ?

**Comment by MathieuTurcotte** [comment]
Pushed w/ 2.5.0.
