### ISSUE TITLE
Strategy with a Exponential jittered backoff

### ISSUE THREAD

**Issue by loretoparisi** [MathieuTurcotte/node-backoff#19]
A possibile alternative exponential strategy to implment could be a jittered exponential backoff strategy as depicted in the Spotify SDK [SPTDataLoader](https://github.com/spotify/SPTDataLoader#using-the-jittered-exponential-timer)

**Comment by MathieuTurcotte** [comment]
It's already there. You can specify a randomization factor.

**Comment by loretoparisi** [comment]
@MathieuTurcotte Yes I have realized after using the library! thank you.
